-- 1. the count of distinct cities in the dataset is -- distinct cities are 3 .
select COUNT(DISTINCT (city)) as distinct_cities from amazon;


-- 2. For each branch,the corresponding city is -- Ans : A = Yangon, B = Mandalay , C = Naypyitaw. 
select branch,city from amazon
group by branch,city
order by branch;

-- 3. the count of distinct product lines in the dataset -- Ans : count is 6.
select COUNT(DISTINCT product_line) as count_of_distinct_product_lines from amazon;


-- 4.payment method occurs most frequently -- Ans : 'Ewallet'.
select payment,count(payment) as payment_method_most_frequent from amazon
group by payment
order by count(Payment) desc 
limit 1;

-- 5. product line has the highest sales: is Ans: 'Electronic accessories' with no of units sold is 971.
select Product_line,sum(quantity) as no_of_units_of_sold from amazon
group by Product_line
order by no_of_units_of_sold desc
limit 1;


-- 6. revenue is generated each month -- Ans: the below code give the answer. by the analysis we observe that in second month the revenue is decreased by 
-- appx 16.40% . And in the third month it is increased by appx 12.59%. 
 select month(str_to_date(Date,'%d-%m-%Y')) as month,sum(total) as revenue_generated_by_month from  amazon
 group by month
 ORDER BY revenue_generated_by_month desc;
 
 -- 7.The month in which the cost of goods sold reached its peak is -- Ans: 'January' that is first month.
select  monthname(str_to_date(Date,'%d-%m-%Y')) as month,sum(cogs) as pick_of_cost_goods from  amazon
group by month
ORDER BY pick_of_cost_goods desc 
limit 1;

-- 8.product line generated the highest revenue is: Ans: 'Food and beverages' and highest Revenue generated is  '56144.844000000005'.
SELECT product_line,sum(total) as highest_revenue_generated from amazon 
group by Product_line 
order by highest_revenue_generated desc
limit 1;

-- 9. the city where the highest revenue recorded is. Ans:'Naypyitaw' and revenue generated by this city is '110568.70649999994'.
select city,sum(total) as highest_revenue_generated from amazon 
GROUP BY city 
ORDER BY highest_revenue_generated desc 
limit 1;

-- 10. product line incurred the highest Value Added Tax is. Ans: 'Food and beverages' and tax incurred is '2673.5639999999994'
select product_line,sum(tax) as highest_tax from amazon
group by product_line
order by highest_tax desc
limit 1 ;

	
-- 11.For each product line, add a column indicating "Good" if its sales are above average, otherwise "Bad." 
with total_sales as(
select Product_line,sum(total) as total_sale from amazon
group by Product_line
),
average_sales as(
select AVG(total_sale) as average_sale from total_sales
)

select t.product_line,t.total_sale,
case 
when t.total_sale > a.average_sale then 'Good'
else 'Bad' 
end as Performance
from total_sales as t , average_sales a;

 -- 12. the branch that exceeded the average number of products sold.-- Ans: 'A'
 with total_no_of_products_sold_in_branch as(select branch,sum(Quantity) as 
 total_products_sold from amazon
 group by branch),
 average_products_sold_in_branch as(
 select avg(total_products_sold) as average_products_sold 
 from total_no_of_products_sold_in_branch)
 
 select t.branch 
 from total_no_of_products_sold_in_branch t , average_products_sold_in_branch a
 where t.total_products_sold > a.average_products_sold ;
 
 -- 13. product line is most frequently associated with each gender. Ans: --
WITH rank_extract as (select gender,product_line,count(*) as counts, 
RANK() OVER (PARTITION BY Gender ORDER BY Count(*) DESC) AS Rank_ from amazon
group by gender,Product_line),most_frequent_a_in_gender as(
select product_line,gender,counts from rank_extract 
where rank_= 1)

select product_line,gender,counts  as most_frequent from most_frequent_a_in_gender ;


-- 14.the average rating for each product line. -- Ans:
select product_line,avg(rating) as Average_rating_of_each_product_line from amazon 
group by Product_line 
order by Average_rating_of_each_product_line desc;
/*
please refer the next docement for 15-28 questions answers.
*/

